[platformio]
default_envs = teensy41
src_dir = src
include_dir = include
lib_dir = ../../libs

[env:teensy41]
platform = https://github.com/tsandmann/platform-teensy.git#f2a89fab6fbe936dc383a6565872eb30545984a6
board = teensy41
framework = arduino
lib_deps =
  https://github.com/tsandmann/freertos-teensy.git#b1943409de50e0514469ae0fc69a6f9ae17f6118
build_unflags = -std=gnu++14
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Wformat=1
  -DUSB_SERIAL
  -DTEENSY_OPT_FASTER_LTO
  -I../../interfaces/generated/c
upload_protocol = teensy-cli
upload_flags = -v
