#!/usr/bin/env python3
"""Generate deterministic C/C++ constants from JSON-compatible YAML catalogs."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


CATALOG_PATHS = (
    ("source_ids", Path("common/interfaces/catalog/source_ids.yaml")),
    ("reason_codes", Path("common/interfaces/catalog/reason_codes.yaml")),
    ("wire_messages", Path("platforms/loonar/interfaces/catalog/wire_messages.yaml")),
)


def parse_int(value: Any) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        return int(value, 0)
    raise ValueError(f"expected integer, got {type(value).__name__}")


def load_catalog(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as stream:
        data = json.load(stream)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: catalog root must be an object")
    return data


def validate_catalog(data: dict[str, Any], path: str = "<memory>") -> None:
    width = parse_int(data.get("width_bits"))
    if width not in (8, 16, 32):
        raise ValueError(f"{path}: width_bits must be 8, 16, or 32")
    maximum = (1 << width) - 1
    prefix = data.get("constant_prefix")
    if not isinstance(prefix, str) or not prefix:
        raise ValueError(f"{path}: constant_prefix is required")

    reserved = []
    for item in data.get("reserved", []):
        start = parse_int(item["start"])
        end = parse_int(item["end"])
        if start < 0 or end < start or end > maximum:
            raise ValueError(f"{path}: invalid reserved range {start:#x}-{end:#x}")
        reserved.append((start, end))

    names: set[str] = set()
    identifiers: set[int] = set()
    entries = data.get("entries")
    if not isinstance(entries, list) or not entries:
        raise ValueError(f"{path}: entries must be a non-empty array")
    for entry in entries:
        name = entry.get("name")
        if not isinstance(name, str) or not name or not name.replace("_", "").isalnum():
            raise ValueError(f"{path}: invalid entry name {name!r}")
        identifier = parse_int(entry.get("id"))
        if name in names:
            raise ValueError(f"{path}: duplicate name {name}")
        if identifier in identifiers:
            raise ValueError(f"{path}: duplicate id {identifier:#x}")
        if identifier < 0 or identifier > maximum:
            raise ValueError(f"{path}: id {identifier:#x} exceeds {width}-bit range")
        if any(start <= identifier <= end for start, end in reserved):
            raise ValueError(f"{path}: id {identifier:#x} is reserved")
        names.add(name)
        identifiers.add(identifier)


def load_all(root: Path) -> list[dict[str, Any]]:
    catalogs = []
    for name, relative_path in CATALOG_PATHS:
        path = root / relative_path
        catalog = load_catalog(path)
        if catalog.get("catalog") != name:
            raise ValueError(f"{path}: catalog name must be {name!r}")
        validate_catalog(catalog, str(path))
        catalogs.append(catalog)
    return catalogs


def hex_literal(identifier: int, width: int) -> str:
    digits = width // 4
    return f"0x{identifier:0{digits}X}u"


def emit_c(catalogs: list[dict[str, Any]]) -> str:
    lines = [
        "/* Generated by tools/gen_catalog.py. Do not edit. */",
        "#ifndef LOONAR_GENERATED_INTERFACE_IDS_H",
        "#define LOONAR_GENERATED_INTERFACE_IDS_H",
        "",
    ]
    for catalog in catalogs:
        width = parse_int(catalog["width_bits"])
        prefix = catalog["constant_prefix"]
        lines.append(f"/* {catalog['catalog']} */")
        for entry in sorted(catalog["entries"], key=lambda item: parse_int(item["id"])):
            lines.append(
                f"#define {prefix}_{entry['name']} {hex_literal(parse_int(entry['id']), width)}"
            )
        lines.append("")
    lines.extend(["#endif", ""])
    return "\n".join(lines)


def emit_cpp(catalogs: list[dict[str, Any]]) -> str:
    lines = [
        "// Generated by tools/gen_catalog.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace loonar::interface_ids {",
    ]
    type_names = {8: "std::uint8_t", 16: "std::uint16_t", 32: "std::uint32_t"}
    for catalog in catalogs:
        width = parse_int(catalog["width_bits"])
        prefix = catalog["constant_prefix"].removeprefix("LNR_").lower()
        lines.append(f"namespace {prefix} {{")
        for entry in sorted(catalog["entries"], key=lambda item: parse_int(item["id"])):
            lines.append(
                f"inline constexpr {type_names[width]} {entry['name']} = "
                f"{hex_literal(parse_int(entry['id']), width)};"
            )
        lines.append(f"}}  // namespace {prefix}")
        lines.append("")
    lines.extend(["}  // namespace loonar::interface_ids", ""])
    return "\n".join(lines)


def emit_markdown(catalogs: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated Interface Constants",
        "",
        "> Generated by `tools/gen_catalog.py`; edit the source catalogs instead.",
        "",
    ]
    for catalog in catalogs:
        width = parse_int(catalog["width_bits"])
        lines.extend(
            [
                f"## {catalog['catalog']}",
                "",
                "| ID | Name | Description |",
                "| ---: | --- | --- |",
            ]
        )
        for entry in sorted(catalog["entries"], key=lambda item: parse_int(item["id"])):
            identifier = parse_int(entry["id"])
            lines.append(
                f"| `0x{identifier:0{width // 4}X}` | `{entry['name']}` | "
                f"{entry.get('description', '')} |"
            )
        lines.append("")
    return "\n".join(lines)


def outputs(root: Path, catalogs: list[dict[str, Any]]) -> dict[Path, str]:
    generated = root / "platforms" / "loonar" / "interfaces" / "generated"
    return {
        generated / "c" / "loonar" / "interface_ids.h": emit_c(catalogs),
        generated / "cpp" / "loonar" / "interface_ids.hpp": emit_cpp(catalogs),
        generated / "interface_catalog.md": emit_markdown(catalogs),
    }


def write_or_check(files: dict[Path, str], check: bool) -> int:
    stale = []
    for path, content in files.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        for path in stale:
            print(f"stale generated file: {path}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        catalogs = load_all(root)
        return write_or_check(outputs(root, catalogs), args.check)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
