[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
monitor_filters = log2file
lib_deps =
    adafruit/Adafruit LIS3MDL@^1.2.5
    adafruit/Adafruit MAX31865 library@^1.6.2
    adafruit/Adafruit MLX90614 Library@^2.1.6
