[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy@5.1.0
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
extra_scripts = pre:diagnostic_build.py
build_flags = -DUSB_SERIAL
lib_deps =
  https://github.com/adafruit/Adafruit_BNO08x.git#525d050e1583a7444f18d020c2cdea70471fb77f
  adafruit/Adafruit BusIO@1.17.4
  adafruit/Adafruit Unified Sensor@1.1.15

[env:mkrzero]
platform = atmelsam@8.3.0
board = mkrzero
framework = arduino
monitor_speed = 115200
extra_scripts = pre:diagnostic_build.py
build_flags =
  -DBNO_MKR_SOFT_SPI
  -Wl,-u,_printf_float
lib_deps = ${env:teensy41.lib_deps}

[env:teensy41_uart]
extends = env:teensy41
build_flags = ${env:teensy41.build_flags} -DBNO_TEENSY_UART
